package generate

import (
	"bytes"
	"fmt"

	"github.com/honoka/meshctl/internal/config"
	"github.com/honoka/meshctl/internal/mesh"
)

// RouterOSGenerator produces .rsc scripts for MikroTik RouterOS devices.
type RouterOSGenerator struct {
	cfg       *config.Config
}

// NewRouterOSGenerator creates a RouterOS config generator.
func NewRouterOSGenerator(cfg *config.Config) *RouterOSGenerator {
	return &RouterOSGenerator{cfg: cfg}
}

// GenerateWireguard produces a wireguard.rsc script.
func (g *RouterOSGenerator) GenerateWireguard(node *config.Node, peers []WGPeerConfig) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "# WireGuard configuration for %s\n", node.Name)
	fmt.Fprintf(&buf, "# Generated by meshctl — do not edit manually\n\n")

	// Create WireGuard interface if it doesn't exist.
	for _, p := range peers {
		iface := WGInterfaceName(g.cfg.Global.WGIfacePrefix, p.Name)
		fmt.Fprintf(&buf, ":if ([:len [/interface/wireguard/find name=\"%s\"]] = 0) do={\n", iface)
		fmt.Fprintf(&buf, "  /interface/wireguard/add name=\"%s\" listen-port=%d mtu=1420\n", iface, p.ListenPort)
		fmt.Fprintf(&buf, "}\n\n")
	}

	// Add/update peers.
	for _, p := range peers {
		iface := WGInterfaceName(g.cfg.Global.WGIfacePrefix,p.Name)
		fmt.Fprintf(&buf, "# Peer: %s\n", p.Name)
		fmt.Fprintf(&buf, ":if ([:len [/interface/wireguard/peers/find interface=\"%s\" public-key=\"%s\"]] = 0) do={\n",
			iface, p.PublicKey)
		fmt.Fprintf(&buf, "  /interface/wireguard/peers/add interface=\"%s\" public-key=\"%s\" endpoint-address-list=\"\" endpoint-port=0 allowed-address=0.0.0.0/0,::/0",
			iface, p.PublicKey)
		if p.Endpoint != "" {
			fmt.Fprintf(&buf, " endpoint=\"%s\"", p.Endpoint)
		}
		if p.KeepAlive > 0 {
			fmt.Fprintf(&buf, " persistent-keepalive=%d", p.KeepAlive)
		}
		fmt.Fprintf(&buf, "\n}\n\n")
	}

	return buf.Bytes(), nil
}

// GenerateOSPF produces an ospf.rsc script.
func (g *RouterOSGenerator) GenerateOSPF(node *config.Node, links []mesh.Link) ([]byte, error) {
	nodeLinks := mesh.LinksForNode(links, node.Name)
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "# OSPF configuration for %s\n", node.Name)
	fmt.Fprintf(&buf, "# Generated by meshctl — do not edit manually\n\n")

	// Remove existing meshctl-managed interface-templates.
	fmt.Fprintf(&buf, "/routing/ospf/interface-template/remove [find where comment~\"meshctl\"]\n\n")

	for _, l := range nodeLinks {
		peerName := l.PeerName(node.Name)
		iface := WGInterfaceName(g.cfg.Global.WGIfacePrefix,peerName)

		// RouterOS only uses OSPFv2 (V4LL mode).
		selfAddr := l.SelfAddr(node.Name)
		peerAddr := l.PeerAddr(node.Name)
		if !selfAddr.IsValid() || !peerAddr.IsValid() {
			continue
		}

		// Set interface address (PTP format: local/32 with network=peer).
		fmt.Fprintf(&buf, ":if ([:len [/ip/address/find interface=\"%s\" address~\"%s\"]] = 0) do={\n",
			iface, selfAddr.Addr().String())
		fmt.Fprintf(&buf, "  /ip/address/add interface=\"%s\" address=%s/32 network=%s\n",
			iface, selfAddr.Addr(), peerAddr.Addr())
		fmt.Fprintf(&buf, "}\n\n")

		// Add OSPF interface-template.
		fmt.Fprintf(&buf, "/routing/ospf/interface-template/add interfaces=\"%s\" area=%s cost=100 type=ptp comment=\"meshctl-%s\"\n\n",
			iface, g.cfg.Global.OSPFArea, peerName)
	}

	return buf.Bytes(), nil
}

// GenerateFull produces a complete .rsc script combining WG, addressing, and OSPF.
func (g *RouterOSGenerator) GenerateFull(node *config.Node, peers []WGPeerConfig, links []mesh.Link) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "# Full mesh configuration for %s\n", node.Name)
	fmt.Fprintf(&buf, "# Generated by meshctl — do not edit manually\n\n")

	wg, err := g.GenerateWireguard(node, peers)
	if err != nil {
		return nil, err
	}
	buf.Write(wg)

	ospf, err := g.GenerateOSPF(node, links)
	if err != nil {
		return nil, err
	}
	buf.Write(ospf)

	// Loopback address.
	fmt.Fprintf(&buf, "# Loopback\n")
	fmt.Fprintf(&buf, ":if ([:len [/ip/address/find address=\"%s/32\"]] = 0) do={\n", node.Loopback)
	fmt.Fprintf(&buf, "  /ip/address/add address=%s/32 interface=lo\n", node.Loopback)
	fmt.Fprintf(&buf, "}\n")

	return buf.Bytes(), nil
}
