package generate

import (
	"bytes"
	"fmt"

	"github.com/honoka/meshctl/internal/config"
	"github.com/honoka/meshctl/internal/mesh"
)

// RouterOSGenerator produces .rsc scripts for MikroTik RouterOS devices.
type RouterOSGenerator struct {
	cfg *config.Config
}

// NewRouterOSGenerator creates a RouterOS config generator.
func NewRouterOSGenerator(cfg *config.Config) *RouterOSGenerator {
	return &RouterOSGenerator{cfg: cfg}
}

// GenerateWireguard produces a wireguard.rsc script.
func (g *RouterOSGenerator) GenerateWireguard(node *config.Node, peers []WGPeerConfig) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "# WireGuard configuration for %s\n", node.Name)
	fmt.Fprintf(&buf, "# Generated by meshctl — do not edit manually\n\n")

	// Operator-managed tunnel: the WireGuard interface is built by hand on this
	// device, so meshctl emits no WG config (it would clobber the existing
	// keys/endpoint/PSK). Only the OSPF section applies. The interface name(s)
	// the mesh expects come from each fat peer's wg_iface_override.
	if node.WGUnmanaged {
		fmt.Fprintf(&buf, "# wg_unmanaged: WireGuard is operator-managed on this device.\n")
		fmt.Fprintf(&buf, "# meshctl does not generate WG interfaces/peers here — see ospf section.\n")
		return buf.Bytes(), nil
	}

	// Create WireGuard interface if it doesn't exist.
	for _, p := range peers {
		iface := p.Interface
		fmt.Fprintf(&buf, ":if ([:len [/interface/wireguard/find name=\"%s\"]] = 0) do={\n", iface)
		fmt.Fprintf(&buf, "  /interface/wireguard/add name=\"%s\" listen-port=%d mtu=1420\n", iface, p.ListenPort)
		fmt.Fprintf(&buf, "}\n\n")
	}

	// Add/update peers.
	for _, p := range peers {
		iface := p.Interface
		fmt.Fprintf(&buf, "# Peer: %s\n", p.Name)
		fmt.Fprintf(&buf, ":if ([:len [/interface/wireguard/peers/find interface=\"%s\" public-key=\"%s\"]] = 0) do={\n",
			iface, p.PublicKey)
		fmt.Fprintf(&buf, "  /interface/wireguard/peers/add interface=\"%s\" public-key=\"%s\" endpoint-address-list=\"\" endpoint-port=0 allowed-address=0.0.0.0/0,::/0",
			iface, p.PublicKey)
		if p.Endpoint != "" {
			fmt.Fprintf(&buf, " endpoint=\"%s\"", p.Endpoint)
		}
		if p.KeepAlive > 0 {
			fmt.Fprintf(&buf, " persistent-keepalive=%d", p.KeepAlive)
		}
		fmt.Fprintf(&buf, "\n}\n\n")
	}

	return buf.Bytes(), nil
}

// GenerateOSPF produces an ospf.rsc script with dual-stack OSPF.
//
// IPv4 runs over OSPFv2 on the 169.254 PTP addresses, because RouterOS lacks
// RFC 5838 (the IPv4 address-family the Linux fat nodes use inside OSPFv3).
// IPv6 runs over native OSPFv3 on the interface's fe80 link-local, which
// RouterOS supports — so v6 rides the same tunnels even though v4 cannot.
//
// Two meshctl-owned instances (meshctl-v2 / meshctl-v3) and their backbone
// areas are created idempotently (check-before-add, so re-imports don't flap
// adjacencies). Interface-templates are removed and re-added on each import so
// cost/timer changes take effect; meshctl-owned objects are tagged with a
// "meshctl" comment and never touch operator-managed OSPF.
func (g *RouterOSGenerator) GenerateOSPF(node *config.Node, links []mesh.Link) ([]byte, error) {
	nodeLinks := mesh.LinksForNode(links, node.Name)
	var buf bytes.Buffer

	hello := g.cfg.Global.OSPFHello
	dead := g.cfg.Global.OSPFDead
	area := g.cfg.Global.OSPFArea

	fmt.Fprintf(&buf, "# OSPF configuration for %s\n", node.Name)
	fmt.Fprintf(&buf, "# Generated by meshctl — do not edit manually\n\n")

	// Remove existing meshctl-managed interface-templates (re-added below).
	fmt.Fprintf(&buf, "/routing/ospf/interface-template/remove [find where comment~\"meshctl\"]\n\n")

	// Ensure the meshctl OSPF instances + backbone areas exist. router-id is the
	// node's loopback (a 32-bit id, used for both the v2 and v3 instance).
	fmt.Fprintf(&buf, ":if ([:len [/routing/ospf/instance/find name=meshctl-v2]] = 0) do={\n")
	fmt.Fprintf(&buf, "  /routing/ospf/instance/add name=meshctl-v2 version=2 router-id=%s comment=\"meshctl\"\n", node.Loopback)
	fmt.Fprintf(&buf, "}\n")
	fmt.Fprintf(&buf, ":if ([:len [/routing/ospf/area/find name=meshctl-v2-backbone]] = 0) do={\n")
	fmt.Fprintf(&buf, "  /routing/ospf/area/add name=meshctl-v2-backbone instance=meshctl-v2 area-id=%s comment=\"meshctl\"\n", area)
	fmt.Fprintf(&buf, "}\n")
	fmt.Fprintf(&buf, ":if ([:len [/routing/ospf/instance/find name=meshctl-v3]] = 0) do={\n")
	fmt.Fprintf(&buf, "  /routing/ospf/instance/add name=meshctl-v3 version=3 router-id=%s comment=\"meshctl\"\n", node.Loopback)
	fmt.Fprintf(&buf, "}\n")
	fmt.Fprintf(&buf, ":if ([:len [/routing/ospf/area/find name=meshctl-v3-backbone]] = 0) do={\n")
	fmt.Fprintf(&buf, "  /routing/ospf/area/add name=meshctl-v3-backbone instance=meshctl-v3 area-id=%s comment=\"meshctl\"\n", area)
	fmt.Fprintf(&buf, "}\n\n")

	for _, l := range nodeLinks {
		peerName := l.PeerName(node.Name)
		iface := IfaceNameForPeer(g.cfg.Global.WGIfacePrefix, node, peerName)

		selfAddr := l.SelfAddr(node.Name)
		peerAddr := l.PeerAddr(node.Name)
		if !selfAddr.IsValid() || !peerAddr.IsValid() {
			continue
		}

		fmt.Fprintf(&buf, "# Peer: %s\n", peerName)

		// IPv4 PTP address (local/32 with network=peer) for OSPFv2.
		fmt.Fprintf(&buf, ":if ([:len [/ip/address/find interface=\"%s\" address~\"%s\"]] = 0) do={\n",
			iface, selfAddr.Addr().String())
		fmt.Fprintf(&buf, "  /ip/address/add interface=\"%s\" address=%s/32 network=%s\n",
			iface, selfAddr.Addr(), peerAddr.Addr())
		fmt.Fprintf(&buf, "}\n")

		// IPv4 via OSPFv2.
		fmt.Fprintf(&buf, "/routing/ospf/interface-template/add interfaces=\"%s\" area=meshctl-v2-backbone cost=100 type=ptp hello-interval=%ds dead-interval=%ds comment=\"meshctl-%s\"\n",
			iface, hello, dead, peerName)
		// IPv6 via native OSPFv3 over the interface's fe80 link-local.
		fmt.Fprintf(&buf, "/routing/ospf/interface-template/add interfaces=\"%s\" area=meshctl-v3-backbone cost=100 type=ptp hello-interval=%ds dead-interval=%ds comment=\"meshctl-%s-v6\"\n\n",
			iface, hello, dead, peerName)
	}

	return buf.Bytes(), nil
}

// GenerateFull produces a complete .rsc script combining WG, addressing, and OSPF.
func (g *RouterOSGenerator) GenerateFull(node *config.Node, peers []WGPeerConfig, links []mesh.Link) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "# Full mesh configuration for %s\n", node.Name)
	fmt.Fprintf(&buf, "# Generated by meshctl — do not edit manually\n\n")

	wg, err := g.GenerateWireguard(node, peers)
	if err != nil {
		return nil, err
	}
	buf.Write(wg)

	ospf, err := g.GenerateOSPF(node, links)
	if err != nil {
		return nil, err
	}
	buf.Write(ospf)

	// Loopback address.
	fmt.Fprintf(&buf, "# Loopback\n")
	fmt.Fprintf(&buf, ":if ([:len [/ip/address/find address=\"%s/32\"]] = 0) do={\n", node.Loopback)
	fmt.Fprintf(&buf, "  /ip/address/add address=%s/32 interface=lo\n", node.Loopback)
	fmt.Fprintf(&buf, "}\n")

	return buf.Bytes(), nil
}
